### ISSUE TITLE
Lack of dependency gem definition

### ISSUE THREAD

**Issue by m0cchi** [MagicTheGathering/mtg-sdk-ruby#12]
my env:
```bash
$ ruby -v
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
```

error message:

```bash
/usr/lib/ruby/3.0.0/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem': dry-types is not part of the bundle. Add it to your Gemfile. (Gem::LoadError)
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/roar-1.2.0/lib/roar/coercion.rb:1:in `<top (required)>'
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/mtg_sdk-3.2.1/lib/mtg_sdk/representers/card_representer.rb:2:in `require'
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/mtg_sdk-3.2.1/lib/mtg_sdk/representers/card_representer.rb:2:in `<top (required)>'
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/mtg_sdk-3.2.1/lib/mtg_sdk/card.rb:1:in `require_relative'
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/mtg_sdk-3.2.1/lib/mtg_sdk/card.rb:1:in `<top (required)>'
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/mtg_sdk-3.2.1/lib/mtg_sdk.rb:3:in `require'
        from /home/m0cchi/dev/ruby/mtga-dumper/vendor/bundler/ruby/3.0.0/gems/mtg_sdk-3.2.1/lib/mtg_sdk.rb:3:in `<top (required)>'
```

**Comment by m0cchi** [comment]
It's a roar issue.
